import { Routes } from '@angular/router';
import { LoginComponent } from './login/login.component';
import { SignUpComponent } from './sign-up/sign-up.component';
import { NavegationBarComponent } from './navegation-bar/navegation-bar.component';
import { SplashComponent } from './splash/splash.component';
import { HomeComponent } from './home/home.component';
import { CarrouselHorizontalComponent } from './carrousel-horizontal/carrousel-horizontal.component';
import { ProductSliderComponent } from './product-slider/product-slider.component';
import { TrendTopicComponent } from './trend-topic/trend-topic.component';
import { MostLikedComponent } from './most-liked/most-liked.component';
import { SearcherComponent } from './searcher/searcher.component';
import { SavedSectionsComponent } from './saved-sections/saved-sections.component';
import { SloganLogoComponent } from './slogan-logo/slogan-logo.component';
import { SettingsComponent } from './settings/settings.component';
import { UploadCloth1Component } from './upload-cloth1/upload-cloth1.component';
import { UploadCloth2Component } from './upload-cloth2/upload-cloth2.component';
import { UploadCloth3Component } from './upload-cloth3/upload-cloth3.component';
import { BrandSelectorComponent } from './brand-selector/brand-selector.component';
import { PreviousViewComponent } from './previous-view/previous-view.component';
import { ColorModalComponent } from './color-modal/color-modal.component';
import { ChatsComponent } from './chats/chats.component';
import { PageChatsComponent } from './page-chats/page-chats.component';
import { PageNotificationsComponent } from './page-notifications/page-notifications.component';
import { NotificationsComponent } from './notifications/notifications.component';

export const routes: Routes = [

  {path: '', redirectTo: '/splash', pathMatch: 'full'},
  { path: 'login', component: LoginComponent},
  { path: 'sign-up', component: SignUpComponent },
  { path: 'navegation-bar', component: NavegationBarComponent },
  { path: 'splash', component: SplashComponent },
  { path: 'home', component: HomeComponent },
  { path: 'carrouselHorizontal', component: CarrouselHorizontalComponent },
  { path: 'productSlider', component: ProductSliderComponent },
  { path: 'trendTopic', component: TrendTopicComponent },
  { path: 'mostLiked', component: MostLikedComponent },
  { path: 'searcher', component: SearcherComponent },
  { path: 'savedSections', component: SavedSectionsComponent },
  { path: 'sloganLogo', component: SloganLogoComponent },
  { path: 'settings', component: SettingsComponent },
  { path: 'uploadCloth1', component: UploadCloth1Component },
  { path: 'uploadCloth2', component: UploadCloth2Component },
  { path: 'uploadCloth3', component: UploadCloth3Component },
  { path: 'brandSelector', component: BrandSelectorComponent },
  { path: 'previousView', component: PreviousViewComponent },
  { path: 'colorModal', component: ColorModalComponent },
  { path: 'chats', component: ChatsComponent },
  { path: 'pageChats', component: PageChatsComponent },
  { path: 'pageNotifications', component: PageNotificationsComponent },
  { path: 'notifications', component: NotificationsComponent },
];
